export const data = {
  status: true,
  data: [
    {
      id: "158ad92d-28de-4500-87ad-dcae77dc8137",
      academy: "الاكادمية الاولى",
      academy_id: 1,
      academy_image:
        "https://www.sayan-server.com/storage/academy/image/yTd0NRBBI3bO1SKLFDRi.jpeg",
      category: "ذكاء اصطناعي",
      category_id: 4,
      trainer: "Mrs. Jaida Lynch MD",
      title: "دورة من بوست مان",
      type: "recorded",
      price: 55,
      level: "intermediate",
      status: true,
      image: "courses/Pe2hpe12rLJUspDRNXiLpggF0TJR0ZMM4mSJnGip.png",
      short_content: "وصف مختصر",
      short_video:
        "courses/videos/ZQ6RQplZcDlXPJ2loTs0iPYjf73snIgKFB4dWCx6.mp4",
      gallery: ["courses/gallery/YjQ0RWfrzfR14jNDvyneDccNn0F2g45EZjPyE5TB.png"],
      categories_count: 0,
      created_at: "2025-04-17T17:12:41.000000Z",
      faved: false,
      rates: [],
      rated: false,
      stars: 0,
      code: null,
      in_favorites: false,
    },
    {
      id: "1bc50c7a-e56d-41f5-8cec-4efacbf217a0",
      academy: "الاكادمية الاولى",
      academy_id: 1,
      academy_image:
        "https://www.sayan-server.com/storage/academy/image/yTd0NRBBI3bO1SKLFDRi.jpeg",
      category: null,
      category_id: 1,
      trainer: "Mrs. Jaida Lynch MD",
      title: "تعلم PHP 2",
      type: "recorded",
      price: 299.99,
      level: "intermediate",
      status: true,
      image: "https://www2.0zz0.com/2025/04/11/12/207950663.jpg",
      short_content: "وصف مختصر محدث",
      short_video:
        "courses/videos/mZ2zPoxLioI1FtglNq6GZt7PhbCV3kK7t3rNZMch.mp4",
      gallery: ["courses/gallery/Q1JiZ9atpJC1SkvfoyqAudmUwDhcUlmEnT3c1oJ8.png"],
      categories_count: 0,
      created_at: "2025-02-06T22:08:05.000000Z",
      faved: false,
      rates: [],
      rated: false,
      stars: 3,
      code: null,
      in_favorites: false,
    },
    {
      id: "1bc50c7a-e56d-41f5-8cec-4efacbf217a1",
      academy: "الاكادمية الاولى",
      academy_id: 1,
      academy_image:
        "https://www.sayan-server.com/storage/academy/image/yTd0NRBBI3bO1SKLFDRi.jpeg",
      category: null,
      category_id: 1,
      trainer: "Mrs. Jaida Lynch MD",
      title: "تعلم PHP 3",
      type: "recorded",
      price: 299.99,
      level: "intermediate",
      status: true,
      image: "https://www2.0zz0.com/2025/04/11/12/207950663.jpg",
      short_content: "وصف مختصر محدث",
      short_video:
        "courses/videos/mZ2zPoxLioI1FtglNq6GZt7PhbCV3kK7t3rNZMch.mp4",
      gallery: ["courses/gallery/Q1JiZ9atpJC1SkvfoyqAudmUwDhcUlmEnT3c1oJ8.png"],
      categories_count: 0,
      created_at: "2025-02-06T22:08:05.000000Z",
      faved: false,
      rates: [],
      rated: false,
      stars: 0,
      code: null,
      in_favorites: false,
    },
    {
      id: "22",
      academy: "الاكادمية الاولى",
      academy_id: 1,
      academy_image:
        "https://www.sayan-server.com/storage/academy/image/yTd0NRBBI3bO1SKLFDRi.jpeg",
      category: null,
      category_id: 1,
      trainer: "Mrs. Jaida Lynch MD",
      title: "تجربة تعديل",
      type: "recorded",
      price: 299.99,
      level: "intermediate",
      status: true,
      image: "https://www2.0zz0.com/2025/02/06/09/759918182.jpg",
      short_content: "وصف مختصر محدث",
      short_video:
        "https://azzamhamed.com/wp-content/uploads/2024/11/WhatsApp-Video-2024-10-30-at-8.14.23-PM.mp4",
      gallery: null,
      categories_count: 0,
      created_at: "2025-01-11T14:24:46.000000Z",
      faved: false,
      rates: [],
      rated: false,
      stars: 1,
      code: null,
      in_favorites: false,
    },
    {
      id: "6199e20c-ab79-4708-8d85-96ba219693c5",
      academy: "الاكادمية الاولى",
      academy_id: 1,
      academy_image:
        "https://www.sayan-server.com/storage/academy/image/yTd0NRBBI3bO1SKLFDRi.jpeg",
      category: "ذكاء اصطناعي",
      category_id: 4,
      trainer: "Mrs. Jaida Lynch MD",
      title: "دورة من بوست مان",
      type: "recorded",
      price: 55,
      level: "intermediate",
      status: true,
      image: "courses/e3CMY5413Rk9ClytmBddfyLfpcVLOQDtfqlOlTtz.png",
      short_content: "وصف مختصر",
      short_video: null,
      gallery: [],
      categories_count: 0,
      created_at: "2025-04-18T19:37:54.000000Z",
      faved: false,
      rates: [],
      rated: false,
      stars: 5,
      code: null,
      in_favorites: false,
    },
    {
      id: "66",
      academy: "الاكادمية الاولى",
      academy_id: 1,
      academy_image:
        "https://www.sayan-server.com/storage/academy/image/yTd0NRBBI3bO1SKLFDRi.jpeg",
      category: "ذكاء اصطناعي",
      category_id: 4,
      trainer: "Kevin Stokes",
      title: "Qui dolorem quia perferendis doloremque beatae ut nam pariatur.",
      type: "attend",
      price: 780.88,
      level: "advanced",
      status: true,
      image: "https://www2.0zz0.com/2025/02/06/09/759918182.jpg",
      short_content:
        "Consequuntur dolores ut ut officia aspernatur distinctio sit. Quae minima odit neque veritatis.",
      short_video:
        "https://45.87.80.38:8443/file-manager/backend/direct?id=%2Fhtdocs%2F%E3%80%BD%20No%20credit%20card%20required_2.mp4",
      gallery: null,
      categories_count: 0,
      created_at: "2025-01-11T14:24:49.000000Z",
      faved: false,
      rates: [],
      rated: false,
      stars: 4,
      code: null,
      in_favorites: false,
    },
    {
      id: "e4a69243-f122-4c37-a1d0-31b44ce4331d",
      academy: "الاكادمية الاولى",
      academy_id: 1,
      academy_image:
        "https://www.sayan-server.com/storage/academy/image/yTd0NRBBI3bO1SKLFDRi.jpeg",
      category: "ذكاء اصطناعي",
      category_id: 4,
      trainer: "Mrs. Jaida Lynch MD",
      title: "دورة من بوست مان",
      type: "recorded",
      price: 55,
      level: "intermediate",
      status: true,
      image: "courses/eUBtuzDlN77zsCpaDiRDLA9SPmOfcIOsEkEqt6ZX.png",
      short_content: "وصف مختصر",
      short_video: null,
      gallery: [],
      categories_count: 0,
      created_at: "2025-04-19T18:05:34.000000Z",
      faved: false,
      rates: [],
      rated: false,
      stars: 0,
      code: null,
      in_favorites: false,
    },
  ],
};
